content:
  - name: posts
    label: Posts
    path: '_posts'
    type: collection
    fields: 
      - name: layout
        label: Layout
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: date 
        label: Date 
        type: date
      - name: tags
        label: Tags
        type: string  
      - name: comments
        label: comments
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: pages
    label: Pages
    path: '_pages'
    type: collection
    fields: 
      - name: layout
        label: Layout
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: permalink 
        label: Permalink 
        type: string
      - name: body
        label: Body
        type: rich-text
    
media: assets