# Site settings
title: "Tom Barbereau"
description: > 
  Scientist, researcher, critical thinker.

author: Tom Barbereau
email: johnny@appleseed.com

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tom-barbereau.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

# Collections
collections:
  tags:
    output: true

sass:
    style: compressed

exclude: [vendor]

