baseURL = 'https://www.tom-barbereau.eu/'
languageCode = 'en-us'
title = 'Tom Barbereau'
theme = 'typo'

canonifyURLs = true

[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A technology oriented personal website and blog curated by Tom Barbereau."
googleTagManagerId = "G-X45SFSJKY5" # Your Google Tag Manager ID

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a scientist specialist at TNO (Dutch Organisation for Applied Scientific Research), where my work focuses on the governance of digital technologies and their broader impact on organisations, the economy, and society. 
My current research centres on cryptographic and privacy-enhancing technologies, exploring how these tools are means to foster or obsfucate trust.

In addition, I am a research fellow at the Institute for Information Law (IViR) at the University of Amsterdam. 
There, I contribute to academic teaching — primarily in the areas of blockchain, cryptocurrencies, and decentralised systems — from an interdiciplinary perspective."""

singleDateFormat = '2 Jan 2006'

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Footer
showFooter = true

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/tom.barbereau/"

[[params.social]]
name = "github"
url = "https://github.com/tom-barbereau"

[[params.social]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=qvsfsEMAAAAJ&hl=en"

[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/tom-barbereau.bsky.social"

# Main menu pages
# [[params.menu]]
# name = "home"
# url = "/"

# [[params.menu]]
# name = "posts"
# url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "portfolio"
url = "/portfolio"

[[params.menu]]
name = "talks"
url = "/talks"

[[params.menu]]
name = "contact"
url = "/contact"

# [[params.menu]]
# name = "tags"
# url = "/tags"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'bw'

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[params.umami]
enable = true
websiteId = "f6c4d624-c73d-490b-bbf8-d62bd0bd1c24"
jsLocation = "https://cloud.umami.is/script.js"

[permalinks]
posts = "/posts/:year/:month/:slug/"

[outputs]
home = ["HTML", "RSS", "RobotsTXT"]
